schema_version: 1

context:
  version: "1.8.0"

package:
  name: rpm-sequoia
  version: ${{ version }}

source:
  url: https://github.com/rpm-software-management/rpm-sequoia/archive/refs/tags/v${{ version }}.tar.gz
  sha256: a34de2923f07b2610de82baa42f664850a4caedc23c35b39df315d94cb5dc751

build:
  number: 0
  skip: not linux
  script:
    - export LIBCLANG_PATH=$BUILD_PREFIX/lib
    - cargo build --release
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - install -Dm644 target/x86_64-unknown-linux-gnu/release/librpm_sequoia.so "${PREFIX}/lib/librpm_sequoia.so.1"
    - ln -s librpm_sequoia.so.1 "${PREFIX}/lib/librpm_sequoia.so"
    - install -Dm644 target/release/rpm-sequoia.pc "${PREFIX}/lib/pkgconfig/rpm-sequoia.pc"

requirements:
  build:
    - cargo-bundle-licenses
    - ${{ compiler('rust') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - pkg-config
    - libclang
    - clang
  host:
    - nettle
  run_exports:
    - ${{ pin_subpackage("rpm-sequoia", upper_bound='x.x') }}

tests:
  - script:
      - pkg-config rpm-sequoia --libs
    requirements:
      run:
        - pkg-config
  - package_contents:
      lib:
        - rpm_sequoia

about:
  homepage: https://github.com/rpm-software-management/rpm-sequoia
  license: LGPL-2.0-or-later
  license_file:
    - LICENSE.txt
    - THIRDPARTY.yml
  summary: "An OpenPGP backend for rpm using Sequoia PGP"

extra:
  recipe-maintainers:
    - chrisburr
